### ISSUE TITLE
Traffic not getting routed through SOCKS Proxy

### ISSUE THREAD

**Issue by PfiatDe** [sensepost/wiresocks#2]
Hi,
I am doing some tests and getting some problems regarding the routing. To verify the setup, I am trying to route everything through the SOCKS connection.
```
root@wg /h/r/wiresocks (main)# cat .env
# the upstream proxy server location
#
# supports any of the uri formats in the proxy models
# docs here: https://github.com/xjasonlyu/tun2socks/wiki/Proxy-Models
PROXY_ADDRESS=socks5://192.168.178.113:48501

# target information.
#
# this is where you specify information about the remote network.
# you want to provide the subnets you want to to route to (over
# socks), and a dns server (typically a domain controller) to use
# for the internal domain.

# comma seperated list of routes to route
TARGET_ROUTES=0.0.0.0/0
TARGET_DNS_SERVER=8.8.8.8
TARGET_ROOT_DOMAIN=io

# wireguard information.
#
# this is information about where your wireguard server is
# available, how many peers would want to connect to it and
# which port to use for wireguard.

# external host where this wireguard server will be reachable
WG_HOST=192.168.178.113
# number of wireguard client (peer) configurations to generate
WG_PEERS=1
WG_UDP_PORT=51820
```
Then I set up a  SOCKS Port via SSH (-D 48501). If I now make some curl (curl.exe ipinfo.io) from the windows machine, it uses the IP address from my ISP not the server with the SOCKS. The wireguard connection seems to work on the client. So I expect the issue on setting the routes on the Docker side.
Is there anything missing?

**Comment by cablethief** [comment]
It doesnt feel as though you are missing anything. Can the tun2socks container reach the socks port, I see that you have your socks listening externally. Could you maybe show a bit more of the networking setup for your situation.

**Comment by PfiatDe** [comment]
Just played a little bit more with this in a AD Environment. The Problem was indeed, that the SOCKS Proxy was not reachable, as I was also using a OpenVPN Tunnel and ssh -D which seems to interfere somehow.
`docker compose logs -f` brought the correct hint.
`wiresocks  | time="2022-10-26T05:25:07Z" level=warning msg="[TCP] dial 192.168.x.x:53: connect to 192.168.178.126:9050: dial tcp 192.168.178.126:9050: connect: connection refused"
`
Another problem was, that in the wireguard config the 0.0.0.0/0 did not work to forward all traffic.
And a last point is, that ping is showing a strange behaviour, as all requests are getting answered, I think by the docker container somehow.
From the Windows System:
`PS C:\Windows\system32> ping 192.168.4.196

Pinging 192.168.4.196 with 32 bytes of data:
Reply from 192.168.4.196: bytes=32 time<1ms TTL=63
Reply from 192.168.4.196: bytes=32 time=1ms TTL=63
Reply from 192.168.4.196: bytes=32 time=1ms TTL=63
Reply from 192.168.4.196: bytes=32 time=1ms TTL=63

Ping statistics for 192.168.4.196:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms`
From the Implant
`130 root@##### ~ # ping 192.168.4.196                                            :(
PING 192.168.4.196 (192.168.4.196) 56(84) bytes of data.
From 192.168.5.190 icmp_seq=1 Destination Host Unreachable
From 192.168.5.190 icmp_seq=2 Destination Host Unreachable
From 192.168.5.190 icmp_seq=3 Destination Host Unreachable
`
This is very useful, Thanks!

**Comment by RuntimeRacer** [comment]
@PfiatDe so I am running in the same issue with the Wireguard config not forwarding all traffic properly. How did you solve this?

I was able to successfully forward to a single server via proxy when adding it's IP to `TARGET_ROUTES`.

But if I use 0.0.0.0/0, 0.0.0.0/1 & 128.0.0.0/1, or any smaller combo of subnets, it's not routing through the proxy and just dialing to the internet from the Server directly.

I tried manually changing the routing behaviour and also tried to use tun2socks instead, but that resulted in complete inability to connect to the outside world

I've been wrapping my head around this the whole day, but didn't make any progress except for that one moment when I was able to confirm that direct IP in the target route is actually working.

**Comment by RuntimeRacer** [comment]
Ok I kinda feel like a noob now - I guess I kinda am with all that networking stuff still.
However, I actually found this post on ServerFault: https://serverfault.com/questions/1011531/how-to-connect-to-socks-tunner-through-openvpn-server

> Solved it using policy based routing.
> ```
> ip route add default via 10.0.0.2 table 101
> ip rule add from 10.8.0.2 table 101
> ```

For Wireguard setup (with 2 or more peers) I just need to add a routing table for the tunnel in entrypoint.sh and add the netmask for the peers:
```
config_route() {
  #for addr in $(echo "$TUN_INCLUDED_ROUTES" | tr ',' '\n'); do
  #  ip route add $addr dev $TUN
  #done
  ip route add default via 198.18.0.1 dev $TUN table 101
  ip rule add from 10.13.13.0/24 table 101
}
```
And now all traffic from peers is being routed through the Socks Proxy.

**Comment by cablethief** [comment]
That's awesome, I will need to look into this a bit myself. Maybe it results in a more robust solution. 

Regarding the ping, there are a bunch of weird nuances that happen. For example nmap through this solution tends to return everything as open, I believe this is due to how tun2socks handles the connection. Other weird things happen depending on how compliant the actual socks proxy being used is (UDP being the most often uncompliant).

**Comment by PfiatDe** [comment]
For my usecase it was enough to specify some smaller subnets like 192.168.0.1/24 and not to use OpenVPN in the same VM. 
0.0.0.0/0 seems not to work and othere VPNs interfere with the wireguard setup.

And you should keep in mind that ping and also nmap (with -sT, -sS should work) is doing strange stuff. However nmap through a socks tunnel is not pure fun anyway :) Rubeus and impacket was working great.

**Comment by cablethief** [comment]
I only use it for internal access so don't really do the whole 0.0.0.0/0, so i can see how that slipped by
