### ISSUE TITLE
Feature Request: Additional Domains

### ISSUE THREAD

**Issue by definitivetofu** [sensepost/wiresocks#6]
It would be great if additional domains could be provided in the `.env` file which would be mapped through for resolution by CoreDNS.

For example the below in `.env`

```
TARGET_DOMAINS=example.org,example.net
```

would translate to the following in Corefile

```
example.net {
    loop
    log
    forward . 10.10.10.10:53 {
        force_tcp
    }
}
example.com {
    loop
    log
    forward . 10.10.10.10:53 {
        force_tcp
    }
}
```

**Comment by cablethief** [comment]
Feels like a reasonable request, Ill try mock something up

**Comment by cablethief** [comment]
Heyo, seems @nurfed1 did this in a pull request. So yay!
